In [1]:
import numpy as np
from sklearn import preprocessing, model_selection, neighbors
import pandas as pd

df =pd.read_csv('breast-cancer-wisconsin.data', index_col=0)
df.head()

,clump_thickness,unif_cell_size,unif_cell_shape,marginal_adhesion,single_epith_cell_size,bare_nuclei,bland_chrom,norm_nucleoli,mitosis,class
id,,,,,,,,,,
1000025,5,1,1,1,2,1,3,1,1,2
1002945,5,4,4,5,7,10,3,2,1,2
1015425,3,1,1,1,2,2,3,1,1,2
1016277,6,8,8,1,3,4,3,7,1,2
1017023,4,1,1,3,2,1,3,1,1,2

In [2]:
#df.set_index('clump_thickness')
print(df.dtypes)

#df.drop('id', axis=1, inplace=True)

df.replace('?', -99999, inplace=True)

df['bare_nuclei'] =df['bare_nuclei'].astype(np.int64)


print(df.dtypes)
df.head()

clump_thickness            int64
unif_cell_size             int64
unif_cell_shape            int64
marginal_adhesion          int64
single_epith_cell_size     int64
bare_nuclei               object
bland_chrom                int64
norm_nucleoli              int64
mitosis                    int64
class                      int64
dtype: object
clump_thickness           int64
unif_cell_size            int64
unif_cell_shape           int64
marginal_adhesion         int64
single_epith_cell_size    int64
bare_nuclei               int64
bland_chrom               int64
norm_nucleoli             int64
mitosis                   int64
class                     int64
dtype: object

,clump_thickness,unif_cell_size,unif_cell_shape,marginal_adhesion,single_epith_cell_size,bare_nuclei,bland_chrom,norm_nucleoli,mitosis,class
id,,,,,,,,,,
1000025,5,1,1,1,2,1,3,1,1,2
1002945,5,4,4,5,7,10,3,2,1,2
1015425,3,1,1,1,2,2,3,1,1,2
1016277,6,8,8,1,3,4,3,7,1,2
1017023,4,1,1,3,2,1,3,1,1,2

In [3]:
X =np.array(df.drop('class', axis=True))
y =np.array(df['class'])

X_train, X_test, y_train, y_test =model_selection.train_test_split(X, y, test_size= 0.2)

clf =neighbors.KNeighborsClassifier()
clf.fit(X_train, y_train)

accuracy =clf.score(X_test, y_test)
print(accuracy)

0.9714285714285714

In [4]:
eg_set =np.array([4,2,1,1,1,2,3,2,1])
#    eg_set =eg_set.reshape(1, -1)

predict =clf.predict(eg_set)
predict

ValueError: Expected 2D array, got 1D array instead:
array=[4 2 1 1 1 2 3 2 1].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [5]:
from sklearn import svm

clf_2 =svm.SVC()
clf_2.fit(X_train, y_train)

accuracy_2 =clf_2.score(X_test, y_test)
print(accuracy_2)

0.9642857142857143

C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)